### PR TITLE
setting up global architecture and contributions guidelines

### PR DESCRIPTION
**Pull request by baimamboukar**

### CODE REVIEW

**Review by sas-bergson — CHANGES_REQUESTED** [review]
the staff management folder is useless and does not correpsond to any standard folder expected from a professional C++ project. (This should be deleted immediatly)
The docs folder is ok
The src folder is ok
All folders are empty and raise the issue of why a pull-request was raised...
Please keep in mind that a pull request means there has been enough changes on files and code thus justifying the time and efforts of reviewers going through your files, cloning your branch to verify that your code is breaking and so on...
Do not raise a pull-request is you have not submitted enough code justifying for reviewers to invest time and sleep in evaluating your progress....
This is a matter of common courtesy!!!!

Finally no merge with the MAIN branch will be allowed until your code has provided full conformance to professional coding standards... 

divide your classes and packages among the team members making sure each team member has a sub branch formthe module branch... commits to your individual branches then create pull requests on your mocule branch when you have completed your class and its unit tests ...

In the feature, pull-requests done for merging to the main branch will be automatically dismissed and closes !!!!!

Tip... Clone the default staff branch in order to start your project from scratch with the right approach... Do not create some nonsense folder before asking for advice...
Good luck !!!!!

**Comment by baimamboukar** [comment]
Hello sir!
Thanks for your feedback....

- I opened this pull request to let you know that there is a task I'm working on
- I doesn't mean in any way that it should be directly reviewed
- I will be adding more commits to the pull requests, until the number of commits is worth for a review
- Once I'm done with the task, I will request for a review

**I personnaly think that it is the best way to keep track of the task you are working on, since the main branch is locked and protected from a direct commit**

Thanks for collaborating !

**Comment by sas-bergson** [comment]
@baimamboukar 
I understand your point of view and I would like to suggest something.
In case you raise a pull-request just for notifying that there is a task I'm working on, could you make sure the description and title attached to the pull-request match your intention???
It will help us dodge and close these when we acknowledge your notification...
Thank you for time!!!

Please it looks like there's a conflict between the original readme.md and yours. Normally a readme.md is supposed to be updated form the top in the reverse chronological order meaning, the latest updates are added on top of the oldest updates.
Please let us keep this standard which is adopted on many other projects hosted here on GitHub

**Comment by sas-bergson** [comment]
@baimamboukar 
Finally I would like to close this pull-request because it is raised for a merge to the main branch which is too early.
Raise another pull request against you rmodule branch which is the **staff branch** 
All your pull-request should lead to a merge on this module branch once your code is reviewed.
Thank you for your time !!!

**Comment by baimamboukar** [comment]
> @baimamboukar 
> I understand your point of view and I would like to suggest something.
> In case you raise a pull-request just for notifying that there is a task I'm working on, could you make sure the description and title attached to the pull-request match your intention??? **OKAY SIR, I WILL DO SO**
> It will help us dodge and close these when we acknowledge your notification...
> Thank you for time!!!
> 
> Please it looks like there's a conflict between the original readme.md and yours. Normally a readme.md is supposed to be updated form the top in the reverse chronological order meaning, the latest updates are added on top of the oldest updates.
> Please let us keep this standard which is adopted on many other projects hosted here on GitHub


Hello Sir! Well understood 🎉 Thanks

**Comment by baimamboukar** [comment]
@sas-bergson 

As we're talking about standards... **I feel like** there are some standards of ``OPEN PROJECTS`` that this particular repository doesn't align with

🔻 **Having a contribution guideline line** Projects where people contribute and collaborate usually have a contribution guideline. Most of the time, it is found in a file CONTRIBUTION.md placed at the root of the repository. It states clearly and properly **How to contribute to the project**. It has completed information about the working style and philosophy adopted for the project.... 

- Pull requests and Issues templates
- File naming conventions
- Folder naming conventions 
- Branching policies
- Etc....


🔻 **Project description** In this particular project, I'm not sure I have understood the purpose of the README.md file! Most of the time, this file contains clear and full information about the project itself and/or a demo of the project alongside with a **how to get started**. Like so, any future contribute will have a clear idea of the project before making contributions. As for the commit history or activity log, it can be easily traced by **GitHub commit history** or **git reflog** in local with GIT. Even more, **GITHUB INSIGHTS** has a set of analytics tools (dependency graph, commits, contributors graph) that permits to see **who did what and when**

🔻**Architecture** For a better organisation and ``nearline professional`` architecture, we could have created a central **GitHub organization** to wrap all the projects, each project having its standalone repository. This way, it could have been easier to manage authorization, collaboration, monitoring and management.

**Comment by baimamboukar** [comment]
> @baimamboukar 
> Finally I would like to close this pull-request because it is raised for a merge to the main branch which is too early.
> Raise another pull request against you rmodule branch which is the **staff branch** 
> All your pull-request should lead to a merge on this module branch once your code is reviewed.
> Thank you for your time !!!

Alright Sir! I'll just change the **target merging branch of this pull request** and close it myself! 

**_Please do take in consideration these remarks_** 👆

Thanks for collaborating 🎉🎉🎉

**Pull request closed without merging**
