### PR TITLE
Created Staff-attendance branch for our team

### PR DESCRIPTION
**Pull request by FonyaBrandone**
Added Staff Attendance Team Branch

### CODE REVIEW

**Comment by FonyaBrandone** [comment]
Waiting for branch merging review sir 🙏

**Review by baimamboukar — APPROVED** [review]

**Comment by baimamboukar** [comment]
Hello @FonyaBrandone @sas-bergson !
I have reviewed this....
Seems to be clean!

**Comment by FonyaBrandone** [comment]
Thanks @baimamboukar ☺️

**Comment by baimamboukar** [comment]
> Thanks @baimamboukar ☺️

✌️☄️

**Pull request merged**
