### PR TITLE
Staff working hours

### PR DESCRIPTION
**Pull request by Zama-Ndongmo-Divine**
c++ file format

### CODE REVIEW

**Comment by sas-bergson** [comment]
0 file changes and you guys are already requesting a pull request???? @Xaviemille :lying_face:

**Review by baimamboukar — CHANGES_REQUESTED** [review]
Hello @Zama-Ndongmo-Divine !
The branch has been successfuly created....
But it is not enough for a pull request to be merged!
Please add some changes in your README file! Or in any other file 

A good **pull request** should have more than 0 _files changed_

**Comment by McGoddy** [comment]
Got it @baimamboukar . 

I am still learning a lot about GitHub with YouTube videos and stuffs. But I will make sure I change stuffs.

**Comment by McGoddy** [comment]
Used the wrong account 😅 sorry

**Comment by Zama-Ndongmo-Divine** [comment]
Got it

**Comment by Xaviemille** [comment]
@sas-bergson Sir, in the first commit "creating subbranches" I included cpp files. Whereas, in the second commit "subbranches", I deleted the cpp files. 
Sir this is because I am confused about what exactly you mean by subbranches. Since you asked us to create a main branch, then subbranches.

> 0 file changes and you guys are already requesting a pull request???? @Xaviemille 🤥

**Comment by sas-bergson** [comment]
This pull request is past more than a week now...
tearing this down...

**Pull request closed without merging**
