### PR TITLE
Create staff management branch 🎉

### PR DESCRIPTION
**Pull request by baimamboukar**
Hello @sas-bergson !
### It seems you did not invite anyone to be contributor on your repository! Therefore it is impossible for anyone to directly push commits into your repository.
Github has strictly denied access rights to us! *(I tried to push)*

**To go about, we**
- forked the repository
- applied initial modifications
- commit and pushed changes
- raised a pull request to be mergerd with your main branch

### All our initial changes can be found in this Pull Request!
Thanks for reviewing 🎉

### CODE REVIEW

**Comment by sas-bergson** [comment]
Good morning @baimamboukar 

It's not an omission. **I did this on purpose to make sure it is only those who are really contributing to this project that would be invited as contributors**. And As you can see, it is working. You are the first one to create a pull request for this project, and therefore, you get invited. 

Now let me ask you a question, Why did you fork the project?
I don't have a problem with forking. But I just wanted to know if it would be good to let all students to fork the project and merged from their forks, or if it would have been easier to let them contribute directly on the original repository???

**Comment by baimamboukar** [comment]
Hello sir!
Thanks for your feedback 🎉

I forked the repository because I didn't have access rights to directly push to your repository.....


**The only way for me to contribute, was to fork the repo, commit my changes and raise a pull request**

I think....
The the easiest way to let all those taking this course to contribute, is to invite them to the repo! 

> 🔴 The only to contribute _(using GIT & GitHub)_ without being invited is by **Forking, commiting changes and raising a pull request**

**Comment by sas-bergson** [comment]
Hello @baimamboukar 
Thank you for the quick reply
I just requested for a google sheet having the GitHub Id of all students taking the course so as to add them directly as contributor. Once I get that file everyone will be able to contribute.
**Let me review your pull-request and then merge your work to the main branch.**

**Review by sas-bergson — CHANGES_REQUESTED** [review]
Maybe you guys can avoid putting code samples in the README.md
What is insteresting in this file, would be update on a regular basis a history of the modification you are doing on the branch

**Comment by sas-bergson** [comment]
I just did my review of your pull-request.
waiting for changes to be applied before merging.

Please take sometime to also review my pull-requests.
Why are you guys not commenting and asking question about what I am doing as well?? :roll_eyes:

**Comment by baimamboukar** [comment]
Alright Sir! ☄️

**Comment by FonyaBrandone** [comment]
Ok Sir, we're still waiting for access grant before pushing

**Comment by sas-bergson** [comment]
@FonyaBrandone 
Good morning sir
You have already been granted access
If you don't check if your ID is correct in the Google sheet file that has been shared for the purpose

**Comment by FonyaBrandone** [comment]
Ok Sir, noted with Thanks 🙏

**Comment by Kumopascaline** [comment]
Ok sir ✔️. Thanks

**Comment by sas-bergson** [comment]
@baimamboukar 
Good evening sir
I am still waiting for you to apply the requested changes.
Hope you are working on it.

**Comment by baimamboukar** [comment]
> Maybe you guys can avoid putting code samples in the README.md What is insteresting in this file, would be update on a regular basis a history of the modification you are doing on the branch

Hello @sas-bergson ! I have already applied the requested changes 🚀

**Comment by baimamboukar** [comment]
@sas-bergson Thanks for reviewing and merging 🎉

**Review by Kumopascaline — APPROVED** [review]

**Comment by sas-bergson** [comment]
ok... Noted... 
Lets approve and close the pull-request

**Comment by sas-bergson** [comment]
closed the pull-request

**Pull request merged**
